package backend

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/myczh-1/determinant/internal/ast"
	"github.com/myczh-1/determinant/internal/binding"
	"github.com/myczh-1/determinant/internal/semantic"
)

type GoBackend struct{ Binding *binding.Resolved }

func (GoBackend) Target() string { return "go" }

type goGenerator struct {
	program      *ast.Program
	typeInfo     *semantic.TypeInfo
	objectNames  map[string]string
	fieldNames   map[string]map[string]string
	valueNames   map[string]string
	flowNames    map[string]string
	outputNames  map[string]string
	valueTypes   map[string]string
	usedNames    map[string]bool
	flowCounters map[string]int
	binding      *binding.Resolved
}

func (backend GoBackend) Generate(program *ast.Program, typeInfo *semantic.TypeInfo) (string, error) {
	if program == nil || typeInfo == nil {
		return "", fmt.Errorf("cannot generate Go source without a checked program")
	}
	g := &goGenerator{
		program:      program,
		typeInfo:     typeInfo,
		objectNames:  map[string]string{},
		fieldNames:   map[string]map[string]string{},
		valueNames:   map[string]string{},
		flowNames:    map[string]string{},
		outputNames:  map[string]string{},
		valueTypes:   map[string]string{},
		usedNames:    map[string]bool{},
		flowCounters: map[string]int{},
		binding:      backend.Binding,
	}
	g.prepareNames()
	var b strings.Builder
	g.writeHeader(&b)
	g.writeRuntime(&b)
	g.writeValueTypes(&b)
	g.writeObjects(&b)
	g.writeStores(&b)
	g.writeFixtureLoader(&b)
	for _, flow := range program.Flows {
		g.writeFlow(&b, flow)
	}
	g.writeHTTP(&b)
	return b.String(), nil
}

func (g *goGenerator) prepareNames() {
	for _, valueSet := range g.program.ValueSets {
		name := "Value_" + encodeIdentifier(valueSet.Name)
		g.valueTypes[valueSet.Name] = name
		for _, value := range valueSet.Values {
			g.valueNames[value.Name] = name + "(" + strconv.Quote(value.Name) + ")"
		}
	}
	for _, object := range g.program.Objects {
		g.objectNames[object.Name] = "Object_" + encodeIdentifier(g.objectProgramName(object.Name))
		fields := map[string]string{}
		for _, field := range object.Fields {
			fields[field.Name] = "F_" + encodeIdentifier(g.fieldProgramName(object.Name, field.Name))
		}
		g.fieldNames[object.Name] = fields
	}
	for _, flow := range g.program.Flows {
		g.flowNames[flow.Name] = "flow_" + encodeIdentifier(g.flowProgramName(flow.Name))
		g.outputNames[flow.Name] = "Output_" + encodeIdentifier(flow.Name)
	}
}

func (g *goGenerator) objectProgramName(name string) string {
	if g.binding != nil {
		if entry, ok := g.binding.Objects[name]; ok && entry.ProgramName != "" {
			return entry.ProgramName
		}
	}
	return name
}

func (g *goGenerator) fieldProgramName(object, field string) string {
	if g.binding != nil {
		if entry, ok := g.binding.Objects[object]; ok {
			if mapped, exists := entry.Fields[field]; exists && mapped.ProgramName != "" {
				return mapped.ProgramName
			}
		}
	}
	return field
}

func (g *goGenerator) flowProgramName(name string) string {
	if g.binding != nil {
		if entry, ok := g.binding.Flows[name]; ok && entry.ProgramName != "" {
			return entry.ProgramName
		}
	}
	return name
}

func (g *goGenerator) inputProgramName(flow, input string) string {
	if g.binding != nil {
		if entry, ok := g.binding.Flows[flow]; ok {
			if mapped, exists := entry.Inputs[input]; exists && mapped.ProgramName != "" {
				return mapped.ProgramName
			}
		}
	}
	return input
}

func (g *goGenerator) outputProgramName(flow, output string) string {
	if g.binding != nil {
		if entry, ok := g.binding.Flows[flow]; ok {
			if mapped, exists := entry.Outputs[output]; exists && mapped.ProgramName != "" {
				return mapped.ProgramName
			}
		}
	}
	return output
}

func (g *goGenerator) outputFieldName(flow, output string) string {
	return "F_" + encodeIdentifier(g.outputProgramName(flow, output))
}

func (g *goGenerator) writeHeader(b *strings.Builder) {
	b.WriteString("// Code generated by Determinant. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	for _, item := range []string{"\t\"encoding/json\"", "\t\"fmt\"", "\t\"log\"", "\t\"net/http\"", "\t\"os\"", "\t\"strconv\"", "\t\"strings\"", "\t\"time\""} {
		b.WriteString(item + "\n")
	}
	b.WriteString(")\n\n")
	b.WriteString("const applicationName = " + strconv.Quote(g.program.Name) + "\n\n")
	b.WriteString("var _ = time.Now\nvar _ = log.Fatal\nvar _ = os.Getenv\n\n")
}

func (g *goGenerator) writeRuntime(b *strings.Builder) {
	b.WriteString(`type FlowResult[T any] struct {
	OK    bool
	Value T
	Error string
}

type Money struct {
	Currency string
	Unit     string
	Scale    int
	Minor    int64
}

func moneyFromText(currency, unit string, scale int, text string) (Money, error) {
	text = strings.TrimSpace(text)
	if text == "" { return Money{}, fmt.Errorf("invalid money") }
	negative := strings.HasPrefix(text, "-")
	unsigned := text
	if negative { unsigned = strings.TrimPrefix(unsigned, "-") }
	parts := strings.Split(unsigned, ".")
	if len(parts) > 2 || parts[0] == "" || (len(parts) == 2 && len(parts[1]) > scale) { return Money{}, fmt.Errorf("invalid money") }
	fraction := ""
	if len(parts) == 2 { fraction = parts[1] }
	if len(fraction) < scale { fraction += strings.Repeat("0", scale-len(fraction)) }
	whole, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil { return Money{}, fmt.Errorf("invalid money") }
	minorFraction := int64(0)
	if fraction != "" { minorFraction, err = strconv.ParseInt(fraction, 10, 64); if err != nil { return Money{}, fmt.Errorf("invalid money") } }
	base := int64(1)
	for i := 0; i < scale; i++ { base *= 10 }
	minor := whole*base + minorFraction
	if negative { minor = -minor }
	return Money{Currency: currency, Unit: unit, Scale: scale, Minor: minor}, nil
}

func moneyLiteral(currency, unit string, scale int, text string) Money {
	value, err := moneyFromText(currency, unit, scale, text)
	if err != nil { panic(err) }
	return value
}

func moneyValue(value Money) string {
	negative := value.Minor < 0
	absolute := value.Minor
	if negative { absolute = -absolute }
	base := int64(1)
	for i := 0; i < value.Scale; i++ { base *= 10 }
	whole := absolute / base
	if value.Scale == 0 { if negative { return "-" + strconv.FormatInt(whole, 10) }; return strconv.FormatInt(whole, 10) }
	fraction := strconv.FormatInt(absolute%base, 10)
	if len(fraction) < value.Scale { fraction = strings.Repeat("0", value.Scale-len(fraction)) + fraction }
	if negative { return "-" + strconv.FormatInt(whole, 10) + "." + fraction }
	return strconv.FormatInt(whole, 10) + "." + fraction
}

func assertCompatibleMoney(left, right Money) {
	if left.Currency != right.Currency || left.Unit != right.Unit || left.Scale != right.Scale { panic("incompatible money") }
}

func moneyAdd(left, right Money) Money { assertCompatibleMoney(left, right); left.Minor += right.Minor; return left }
func moneySubtract(left, right Money) Money { assertCompatibleMoney(left, right); left.Minor -= right.Minor; return left }
func moneyMultiply(value Money, factor int64) Money { value.Minor *= factor; return value }
func moneyCompare(left, right Money) int { assertCompatibleMoney(left, right); if left.Minor < right.Minor { return -1 }; if left.Minor > right.Minor { return 1 }; return 0 }
func identityKey(values ...any) string { encoded, _ := json.Marshal(values); return string(encoded) }

func writeJSON(response http.ResponseWriter, status int, value any) {
	response.Header().Set("Content-Type", "application/json")
	response.WriteHeader(status)
	if status != http.StatusNoContent && value != nil { _ = json.NewEncoder(response).Encode(value) }
}

func matchRoute(template, actual string) (map[string]string, bool) {
	clean := func(value string) []string { value = strings.Trim(value, "/"); if value == "" { return nil }; return strings.Split(value, "/") }
	templateParts, actualParts := clean(template), clean(actual)
	if len(templateParts) != len(actualParts) { return nil, false }
	parameters := map[string]string{}
	for index, part := range templateParts {
		if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") { parameters[strings.TrimSuffix(strings.TrimPrefix(part, "{"), "}")] = actualParts[index]; continue }
		if part != actualParts[index] { return nil, false }
	}
	return parameters, true
}

func readBody(request *http.Request) (map[string]json.RawMessage, error) {
	body := map[string]json.RawMessage{}
	if request.Body == nil { return body, nil }
	if err := json.NewDecoder(request.Body).Decode(&body); err != nil { return nil, err }
	return body, nil
}

func readTextPath(value string) (string, error) { if value == "" { return "", fmt.Errorf("missing required field") }; return value, nil }
func readIntegerPath(value string) (int64, error) { if value == "" { return 0, fmt.Errorf("missing required field") }; parsed, err := strconv.ParseInt(value, 10, 64); if err != nil { return 0, fmt.Errorf("invalid integer") }; return parsed, nil }
func readBooleanPath(value string) (bool, error) { if value == "true" { return true, nil }; if value == "false" { return false, nil }; return false, fmt.Errorf("invalid boolean") }
func readRaw(raw json.RawMessage) (any, error) { if len(raw) == 0 { return nil, fmt.Errorf("missing required field") }; var value any; decoder := json.NewDecoder(strings.NewReader(string(raw))); decoder.UseNumber(); if err := decoder.Decode(&value); err != nil { return nil, err }; return value, nil }
func readTextJSON(raw json.RawMessage) (string, error) { var value string; if len(raw) == 0 { return "", fmt.Errorf("missing required field") }; if err := json.Unmarshal(raw, &value); err != nil { return "", fmt.Errorf("invalid text") }; return value, nil }
func readIntegerJSON(raw json.RawMessage) (int64, error) { value, err := readRaw(raw); if err != nil { return 0, err }; number, ok := value.(json.Number); if !ok { return 0, fmt.Errorf("invalid integer") }; parsed, err := strconv.ParseInt(string(number), 10, 64); if err != nil { return 0, fmt.Errorf("invalid integer") }; return parsed, nil }
func readBooleanJSON(raw json.RawMessage) (bool, error) { var value bool; if len(raw) == 0 { return false, fmt.Errorf("missing required field") }; if err := json.Unmarshal(raw, &value); err != nil { return false, fmt.Errorf("invalid boolean") }; return value, nil }
func readMoneyJSON(raw json.RawMessage, currency, unit string, scale int) (Money, error) { value, err := readTextJSON(raw); if err != nil { return Money{}, err }; return moneyFromText(currency, unit, scale, value) }
func readFixtureText(raw json.RawMessage) (string, error) { return readTextJSON(raw) }
func readFixtureInteger(raw json.RawMessage) (int64, error) { return readIntegerJSON(raw) }
func readFixtureBoolean(raw json.RawMessage) (bool, error) { return readBooleanJSON(raw) }
func readFixtureMoney(raw json.RawMessage, currency, unit string, scale int) (Money, error) { return readMoneyJSON(raw, currency, unit, scale) }
func readFixtureTime(raw json.RawMessage) (time.Time, error) {
	value, err := readTextJSON(raw)
	if err != nil { return time.Time{}, err }
	parsed, err := time.Parse(time.RFC3339Nano, value)
	if err != nil || parsed.UTC().Format("2006-01-02T15:04:05.000Z") != value { return time.Time{}, fmt.Errorf("invalid time") }
	return parsed.UTC(), nil
}
func readFixtureValue(raw json.RawMessage, allowed ...string) (string, error) {
	value, err := readTextJSON(raw)
	if err != nil { return "", err }
	for _, candidate := range allowed { if candidate == value { return value, nil } }
	return "", fmt.Errorf("invalid value")
}
func mustFixtureText(raw json.RawMessage) string { value, err := readFixtureText(raw); if err != nil { panic(err) }; return value }
func mustFixtureInteger(raw json.RawMessage) int64 { value, err := readFixtureInteger(raw); if err != nil { panic(err) }; return value }
func mustFixtureBoolean(raw json.RawMessage) bool { value, err := readFixtureBoolean(raw); if err != nil { panic(err) }; return value }
func mustFixtureMoney(raw json.RawMessage, currency, unit string, scale int) Money { value, err := readFixtureMoney(raw, currency, unit, scale); if err != nil { panic(err) }; return value }
func mustFixtureTime(raw json.RawMessage) time.Time { value, err := readFixtureTime(raw); if err != nil { panic(err) }; return value }
func mustFixtureValue(raw json.RawMessage, allowed ...string) string { value, err := readFixtureValue(raw, allowed...); if err != nil { panic(err) }; return value }
func mustFixtureUnsupported() any { panic("invalid fixture: unsupported field type") }
func configuredNow() time.Time {
	value := os.Getenv("DETERMINANT_CLOCK")
	if value == "" { return time.Now().UTC() }
	parsed, _ := time.Parse(time.RFC3339Nano, value)
	return parsed.UTC()
}
func validateRuntimeConfig() error {
	value := os.Getenv("DETERMINANT_CLOCK")
	if value == "" { return nil }
	if _, err := time.Parse(time.RFC3339Nano, value); err != nil { return fmt.Errorf("invalid clock: %s", value) }
	return nil
}

`)
}

func (g *goGenerator) writeValueTypes(b *strings.Builder) {
	for _, valueSet := range g.program.ValueSets {
		name := g.valueTypes[valueSet.Name]
		b.WriteString("type " + name + " string\n\n")
		for _, value := range valueSet.Values {
			b.WriteString("const " + "Value_" + encodeIdentifier(value.Name) + " " + name + " = " + strconv.Quote(value.Name) + "\n")
		}
		b.WriteString("\n")
	}
}

func (g *goGenerator) writeObjects(b *strings.Builder) {
	for _, object := range g.program.Objects {
		b.WriteString("type " + g.objectNames[object.Name] + " struct {\n")
		for _, field := range object.Fields {
			b.WriteString("\t" + g.fieldNames[object.Name][field.Name] + " " + g.goType(field.Type) + " `json:\"" + field.Name + "\"`\n")
		}
		b.WriteString("}\n\n")
	}
}

func (g *goGenerator) writeStores(b *strings.Builder) {
	for _, object := range g.program.Objects {
		if len(object.IdentityFields) == 0 {
			continue
		}
		b.WriteString("var store_" + encodeIdentifier(object.Name) + " = map[string]*" + g.objectNames[object.Name] + "{}\n")
	}
	if len(g.program.Objects) > 0 {
		b.WriteString("\n")
	}
}

func (g *goGenerator) writeFixtureLoader(b *strings.Builder) {
	stored := make([]ast.Object, 0)
	for _, object := range g.program.Objects {
		if len(object.IdentityFields) > 0 {
			stored = append(stored, object)
		}
	}
	b.WriteString("func loadFixtureFromEnv() (err error) {\n")
	b.WriteString("\tdefer func() { if recovered := recover(); recovered != nil { err = fmt.Errorf(\"invalid fixture: %v\", recovered) } }()\n")
	b.WriteString("\tpath := os.Getenv(\"DETERMINANT_FIXTURE\")\n\tif path == \"\" { return nil }\n")
	b.WriteString("\tdata, err := os.ReadFile(path)\n\tif err != nil { return fmt.Errorf(\"read fixture: %w\", err) }\n")
	b.WriteString("\tvar root map[string]json.RawMessage\n\tif err := json.Unmarshal(data, &root); err != nil { return fmt.Errorf(\"invalid fixture JSON: %w\", err) }\n")
	b.WriteString("\tif len(root) != " + strconv.Itoa(len(stored)) + " { return fmt.Errorf(\"invalid fixture: unexpected object set\") }\n")
	for _, object := range stored {
		b.WriteString("\tif _, ok := root[" + strconv.Quote(object.Name) + "]; !ok { return fmt.Errorf(\"invalid fixture: missing " + object.Name + "\") }\n")
		b.WriteString("\tvar rows_" + encodeIdentifier(object.Name) + " []map[string]json.RawMessage\n")
		b.WriteString("\tif err := json.Unmarshal(root[" + strconv.Quote(object.Name) + "], &rows_" + encodeIdentifier(object.Name) + "); err != nil { return fmt.Errorf(\"invalid fixture: " + object.Name + "\") }\n")
		b.WriteString("\tfixtureStore_" + encodeIdentifier(object.Name) + " := map[string]*" + g.objectNames[object.Name] + "{}\n")
		b.WriteString("\tfor _, row := range rows_" + encodeIdentifier(object.Name) + " {\n")
		b.WriteString("\t\tif len(row) != " + strconv.Itoa(len(object.Fields)) + " { return fmt.Errorf(\"invalid fixture: " + object.Name + " fields\") }\n")
		b.WriteString("\t\titem := &" + g.objectNames[object.Name] + "{\n")
		for _, field := range object.Fields {
			b.WriteString("\t\t\t" + g.fieldNames[object.Name][field.Name] + ": ")
			b.WriteString(g.fixtureValueExpression(field.Type, "row["+strconv.Quote(field.Name)+"]"))
			b.WriteString(",\n")
		}
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tkey := " + g.identityExpression("item", object) + "\n")
		b.WriteString("\t\tif _, exists := fixtureStore_" + encodeIdentifier(object.Name) + "[key]; exists { return fmt.Errorf(\"invalid fixture: duplicate " + object.Name + " identity\") }\n")
		b.WriteString("\t\tfixtureStore_" + encodeIdentifier(object.Name) + "[key] = item\n")
		b.WriteString("\t}\n")
	}
	for _, object := range stored {
		b.WriteString("\tstore_" + encodeIdentifier(object.Name) + " = fixtureStore_" + encodeIdentifier(object.Name) + "\n")
	}
	b.WriteString("\treturn nil\n}\n\n")
}

func (g *goGenerator) fixtureValueExpression(typeRef ast.TypeRef, raw string) string {
	resolved := g.resolveType(typeRef)
	switch resolved.Kind {
	case "integer":
		return "mustFixtureInteger(" + raw + ")"
	case "text":
		return "mustFixtureText(" + raw + ")"
	case "boolean":
		return "mustFixtureBoolean(" + raw + ")"
	case "money":
		return "mustFixtureMoney(" + raw + ", " + strconv.Quote(resolved.Currency) + ", " + strconv.Quote(resolved.Unit) + ", " + strconv.Itoa(resolved.Scale) + ")"
	case "time":
		return "mustFixtureTime(" + raw + ")"
	case "value":
		values := make([]string, 0, len(resolved.Values))
		for _, value := range resolved.Values {
			values = append(values, strconv.Quote(value))
		}
		return g.valueTypes[resolved.Name] + "(mustFixtureValue(" + raw + ", " + strings.Join(values, ", ") + "))"
	default:
		return "mustFixtureUnsupported()"
	}
}

func (g *goGenerator) writeFlow(b *strings.Builder, flow ast.Flow) {
	outputName := g.outputNames[flow.Name]
	b.WriteString("type " + outputName + " struct {\n")
	signature := g.typeInfo.FlowSignatures[flow.Name]
	for index, output := range flow.Outputs {
		outputType := semantic.Type{Kind: "unknown"}
		if index < len(signature.Output.Fields) {
			outputType = g.resolveType(signature.Output.Fields[index].Type)
		}
		b.WriteString("\t" + g.outputFieldName(flow.Name, output.Name) + " " + g.goSemanticType(outputType) + " `json:\"" + output.Name + "\"`\n")
	}
	b.WriteString("}\n\n")

	params := make([]string, 0, len(flow.Inputs))
	environment := g.valueEnvironment()
	symbols := map[string]string{}
	for index, input := range flow.Inputs {
		param := fmt.Sprintf("input_%d", index)
		params = append(params, param+" "+g.goType(input.Type))
		symbols[input.Name] = param
		environment[input.Name] = g.resolveType(input.Type)
	}
	functionName := g.flowNames[flow.Name]
	b.WriteString("func " + functionName + "(" + strings.Join(params, ", ") + ") FlowResult[" + outputName + "] {\n")
	state := &emitState{symbols: symbols, environment: environment, counters: map[string]int{}, flowName: flow.Name}
	g.emitStatements(b, flow.Statements, state, "\t", nil)
	b.WriteString("\treturn FlowResult[" + outputName + "]{OK: true, Value: " + outputName + "{\n")
	for _, output := range flow.Outputs {
		outputType := g.expressionType(output.Expression, state.environment)
		b.WriteString("\t\t" + g.outputFieldName(flow.Name, output.Name) + ": " + g.renderExpression(output.Expression, state) + ",\n")
		_ = outputType
	}
	b.WriteString("\t}}\n}\n\n")
}

type emitState struct {
	symbols     map[string]string
	environment map[string]semantic.Type
	counters    map[string]int
	flowName    string
}

type atomicState struct {
	original map[string]string
	staged   map[string]string
	pending  []pendingCreate
}

type pendingCreate struct {
	object string
	symbol string
	key    string
}

func (g *goGenerator) emitStatements(b *strings.Builder, statements []ast.Statement, state *emitState, indent string, atomic *atomicState) {
	for _, statement := range statements {
		switch statement.Kind {
		case "if":
			b.WriteString(indent + "if " + g.renderExpression(statement.Condition, state) + " { return FlowResult[" + g.outputNames[g.currentFlowName(state)] + "]{Error: " + strconv.Quote(statement.Failure) + "} }\n")
		case "conditional":
			b.WriteString(indent + "if " + g.renderExpression(statement.Condition, state) + " {\n")
			child := &emitState{symbols: cloneStrings(state.symbols), environment: cloneTypes(state.environment), counters: state.counters, flowName: state.flowName}
			g.emitStatements(b, statement.Statements, child, indent+"\t", atomic)
			b.WriteString(indent + "}\n")
		case "atomic":
			g.emitAtomic(b, statement.Statements, state, indent)
		case "calculate":
			symbol := fmt.Sprintf("calculation_%d", state.counters["calculate"])
			state.counters["calculate"]++
			b.WriteString(indent + "" + symbol + " := " + g.renderExpression(statement.Expression, state) + "\n")
			state.symbols[statement.Name] = symbol
			state.environment[statement.Name] = g.expressionType(statement.Expression, state.environment)
		case "create":
			g.emitCreate(b, statement, state, indent, atomic)
		case "query":
			g.emitQuery(b, statement, state, indent)
		case "delete":
			g.emitDelete(b, statement, state, indent)
		case "change":
			if atomic != nil {
				g.emitChange(b, statement, state, indent)
			} else {
				g.emitChange(b, statement, state, indent)
			}
		case "execute":
			g.emitExecute(b, statement, state, indent)
		}
	}
}

func (g *goGenerator) emitAtomic(b *strings.Builder, statements []ast.Statement, state *emitState, indent string) {
	transaction := &atomicState{original: map[string]string{}, staged: map[string]string{}}
	for _, statement := range statements {
		if statement.Kind != "change" || statement.Target == nil {
			continue
		}
		root := rootReference(statement.Target)
		original := state.symbols[root]
		if root == "" || original == "" || transaction.staged[root] != "" {
			continue
		}
		staged := fmt.Sprintf("atomic_%d", len(transaction.staged))
		b.WriteString(indent + staged + " := *" + original + "\n")
		b.WriteString(indent + staged + "_ptr := &" + staged + "\n")
		transaction.original[root] = original
		transaction.staged[root] = staged + "_ptr"
	}
	child := &emitState{symbols: cloneStrings(state.symbols), environment: cloneTypes(state.environment), counters: state.counters, flowName: state.flowName}
	for root, staged := range transaction.staged {
		child.symbols[root] = staged
	}
	g.emitStatements(b, statements, child, indent, transaction)
	for _, root := range sortedKeys(transaction.staged) {
		staged := transaction.staged[root]
		b.WriteString(indent + "*" + transaction.original[root] + " = *" + staged + "\n")
	}
	for _, pending := range transaction.pending {
		b.WriteString(indent + "store_" + encodeIdentifier(pending.object) + "[" + pending.key + "] = " + pending.symbol + "\n")
	}
}

func (g *goGenerator) emitCreate(b *strings.Builder, statement ast.Statement, state *emitState, indent string, atomic *atomicState) {
	object, ok := findObject(g.program.Objects, statement.ObjectName)
	if !ok {
		return
	}
	symbol := fmt.Sprintf("created_%d", state.counters["create"])
	state.counters["create"]++
	b.WriteString(indent + symbol + " := &" + g.objectNames[object.Name] + "{\n")
	for _, field := range object.Fields {
		assignment := findAssignment(statement.Assignments, field.Name)
		if assignment != nil {
			b.WriteString(indent + "\t" + g.fieldNames[object.Name][field.Name] + ": " + g.renderExpression(assignment.Expression, state) + ",\n")
		}
	}
	b.WriteString(indent + "}\n")
	key := symbol + "_key"
	b.WriteString(indent + key + " := " + g.identityExpression(symbol, object) + "\n")
	store := "store_" + encodeIdentifier(object.Name)
	if atomic != nil {
		b.WriteString(indent + "if _, exists := " + store + "[" + key + "]; exists { return FlowResult[" + g.outputNames[g.currentFlowName(state)] + "]{Error: " + strconv.Quote(statement.Failure) + "} }\n")
		for _, pending := range atomic.pending {
			if pending.object == object.Name {
				b.WriteString(indent + "if " + pending.key + " == " + key + " { return FlowResult[" + g.outputNames[g.currentFlowName(state)] + "]{Error: " + strconv.Quote(statement.Failure) + "} }\n")
			}
		}
		atomic.pending = append(atomic.pending, pendingCreate{object: object.Name, symbol: symbol, key: key})
	} else {
		b.WriteString(indent + "if _, exists := " + store + "[" + key + "]; exists { return FlowResult[" + g.outputNames[g.currentFlowName(state)] + "]{Error: " + strconv.Quote(statement.Failure) + "} }\n")
		b.WriteString(indent + store + "[" + key + "] = " + symbol + "\n")
	}
	state.symbols[statement.Name] = symbol
	state.environment[statement.Name] = g.resolveType(ast.TypeRef{Kind: "named", Name: object.Name})
}

func (g *goGenerator) emitQuery(b *strings.Builder, statement ast.Statement, state *emitState, indent string) {
	object, ok := findObject(g.program.Objects, statement.ObjectName)
	if !ok {
		return
	}
	candidate := fmt.Sprintf("query_candidate_%d", state.counters["query"])
	symbol := fmt.Sprintf("query_%d", state.counters["query"])
	state.counters["query"]++
	b.WriteString(indent + "var " + symbol + " *" + g.objectNames[object.Name] + "\n")
	b.WriteString(indent + "for _, " + candidate + " := range store_" + encodeIdentifier(object.Name) + " {\n")
	queryState := &emitState{symbols: cloneStrings(state.symbols), environment: cloneTypes(state.environment), counters: state.counters}
	queryState.symbols[statement.Name] = candidate
	queryState.environment[statement.Name] = g.resolveType(ast.TypeRef{Kind: "named", Name: object.Name})
	b.WriteString(indent + "\tif " + g.renderExpression(statement.Condition, queryState) + " { " + symbol + " = " + candidate + "; break }\n")
	b.WriteString(indent + "}\n")
	b.WriteString(indent + "if " + symbol + " == nil { return FlowResult[" + g.outputNames[g.currentFlowName(state)] + "]{Error: " + strconv.Quote(statement.Failure) + "} }\n")
	state.symbols[statement.Name] = symbol
	state.environment[statement.Name] = g.resolveType(ast.TypeRef{Kind: "named", Name: object.Name})
}

func (g *goGenerator) emitDelete(b *strings.Builder, statement ast.Statement, state *emitState, indent string) {
	if statement.Expression == nil || statement.Expression.Kind != "reference" {
		return
	}
	objectType := state.environment[statement.Expression.Name]
	object, ok := findObject(g.program.Objects, objectType.Name)
	if !ok {
		return
	}
	b.WriteString(indent + "delete(store_" + encodeIdentifier(object.Name) + ", " + g.identityExpression(g.renderExpression(statement.Expression, state), object) + ")\n")
}

func (g *goGenerator) emitChange(b *strings.Builder, statement ast.Statement, state *emitState, indent string) {
	if statement.Target == nil {
		return
	}
	b.WriteString(indent + g.renderExpression(statement.Target, state) + " = " + g.renderExpression(statement.Expression, state) + "\n")
}

func (g *goGenerator) emitExecute(b *strings.Builder, statement ast.Statement, state *emitState, indent string) {
	called, ok := g.typeInfo.FlowSignatures[statement.FlowName]
	if !ok {
		return
	}
	result := fmt.Sprintf("executed_%d", state.counters["execute"])
	state.counters["execute"]++
	args := make([]string, 0, len(statement.Inputs))
	for _, input := range statement.Inputs {
		args = append(args, g.renderExpression(input, state))
	}
	b.WriteString(indent + result + " := " + g.flowNames[statement.FlowName] + "(" + strings.Join(args, ", ") + ")\n")
	b.WriteString(indent + "if !" + result + ".OK { return FlowResult[" + g.outputNames[g.currentFlowName(state)] + "]{Error: " + result + ".Error} }\n")
	for index, output := range statement.Outputs {
		if index >= len(called.Output.Fields) {
			break
		}
		field := called.Output.Fields[index]
		name := g.outputFieldName(statement.FlowName, field.Name)
		state.symbols[output] = result + ".Value." + name
		state.environment[output] = g.resolveType(field.Type)
	}
}

func (g *goGenerator) writeHTTP(b *strings.Builder) {
	b.WriteString("func main() {\n")
	b.WriteString("\tif err := validateRuntimeConfig(); err != nil { log.Fatal(err) }\n")
	b.WriteString("\tif err := loadFixtureFromEnv(); err != nil { log.Fatal(err) }\n")
	if len(g.program.HTTPEntries) == 0 {
		b.WriteString("\tfmt.Println(applicationName + \" has no HTTP routes\")\n")
		b.WriteString("}\n")
		return
	}
	b.WriteString("\thttp.HandleFunc(\"/\", handleHTTP)\n")
	b.WriteString("\tport := os.Getenv(\"PORT\")\n\tif port == \"\" { port = \"8080\" }\n")
	b.WriteString("\tlog.Fatal(http.ListenAndServe(\":\"+port, nil))\n}\n\n")
	b.WriteString("func handleHTTP(response http.ResponseWriter, request *http.Request) {\n")
	for _, entry := range g.program.HTTPEntries {
		b.WriteString("\tif request.Method == " + strconv.Quote(entry.Method) + " {\n")
		b.WriteString("\t\tif parameters, matched := matchRoute(" + strconv.Quote(entry.Path) + ", request.URL.Path); matched {\n")
		needsBody := len(entry.BodyMappings) > 0
		if needsBody {
			b.WriteString("\t\t\tbody, err := readBody(request)\n\t\t\tif err != nil { writeJSON(response, http.StatusBadRequest, map[string]string{\"error\": \"invalid request body\"}); return }\n")
		} else {
			b.WriteString("\t\t\tbody := map[string]json.RawMessage{}\n")
			b.WriteString("\t\t\t_ = body\n")
		}
		if len(entry.PathMappings) == 0 {
			b.WriteString("\t\t\t_ = parameters\n")
		}
		flow, ok := findFlow(g.program.Flows, entry.TargetFlow)
		if !ok {
			continue
		}
		for index, input := range flow.Inputs {
			mapping, source, fromPath := g.httpMapping(entry, input.Name)
			variable := fmt.Sprintf("input_%d", index)
			if source == "system" {
				b.WriteString("\t\t\t" + variable + " := configuredNow()\n")
				continue
			}
			read := g.httpReader(input.Type, mapping.SourceName, fromPath)
			b.WriteString("\t\t\t" + variable + ", err := " + read + "\n")
			b.WriteString("\t\t\tif err != nil { writeJSON(response, http.StatusBadRequest, map[string]string{\"error\": err.Error()}); return }\n")
		}
		args := make([]string, 0, len(flow.Inputs))
		for index := range flow.Inputs {
			args = append(args, fmt.Sprintf("input_%d", index))
		}
		result := "httpResult_" + encodeIdentifier(entry.Name)
		b.WriteString("\t\t\t" + result + " := " + g.flowNames[flow.Name] + "(" + strings.Join(args, ", ") + ")\n")
		b.WriteString("\t\t\tif !" + result + ".OK {\n")
		for _, failure := range entry.FailureMappings {
			b.WriteString("\t\t\t\tif " + result + ".Error == " + strconv.Quote(failure.Failure) + " { writeJSON(response, " + strconv.Itoa(failure.Status) + ", map[string]string{\"error\": " + result + ".Error}); return }\n")
		}
		b.WriteString("\t\t\t\twriteJSON(response, http.StatusInternalServerError, map[string]string{\"error\": " + result + ".Error}); return\n\t\t\t}\n")
		if entry.SuccessStatus == 204 {
			b.WriteString("\t\t\twriteJSON(response, http.StatusNoContent, nil); return\n")
		} else {
			b.WriteString("\t\t\twriteJSON(response, " + strconv.Itoa(entry.SuccessStatus) + ", map[string]any{\n")
			signature := g.typeInfo.FlowSignatures[flow.Name]
			for _, output := range signature.Output.Fields {
				expression := result + ".Value." + g.outputFieldName(flow.Name, output.Name)
				b.WriteString("\t\t\t\t" + strconv.Quote(output.Name) + ": " + g.serializeValue(expression, g.resolveType(output.Type)) + ",\n")
			}
			b.WriteString("\t\t\t}); return\n")
		}
		b.WriteString("\t\t}\n\t}\n")
	}
	b.WriteString("\twriteJSON(response, http.StatusNotFound, map[string]string{\"error\": \"route not found\"})\n}\n")
}

func (g *goGenerator) httpMapping(entry ast.HTTPEntry, target string) (ast.HTTPFieldMapping, string, bool) {
	for _, mapping := range entry.PathMappings {
		if mapping.TargetName == target {
			return mapping, "path", true
		}
	}
	for _, mapping := range entry.BodyMappings {
		if mapping.TargetName == target {
			return mapping, "body", false
		}
	}
	for _, mapping := range entry.SystemMappings {
		if mapping.TargetName == target {
			return ast.HTTPFieldMapping{}, "system", false
		}
	}
	return ast.HTTPFieldMapping{}, "", false
}

func (g *goGenerator) httpReader(typeRef ast.TypeRef, source string, fromPath bool) string {
	typeInfo := g.resolveType(typeRef)
	if fromPath {
		pathValue := "parameters[" + strconv.Quote(source) + "]"
		switch typeInfo.Kind {
		case "integer":
			return "readIntegerPath(" + pathValue + ")"
		case "boolean":
			return "readBooleanPath(" + pathValue + ")"
		default:
			return "readTextPath(" + pathValue + ")"
		}
	}
	raw := "body[" + strconv.Quote(source) + "]"
	switch typeInfo.Kind {
	case "integer":
		return "readIntegerJSON(" + raw + ")"
	case "boolean":
		return "readBooleanJSON(" + raw + ")"
	case "money":
		return "readMoneyJSON(" + raw + ", " + strconv.Quote(typeInfo.Currency) + ", " + strconv.Quote(typeInfo.Unit) + ", " + strconv.Itoa(typeInfo.Scale) + ")"
	default:
		return "readTextJSON(" + raw + ")"
	}
}

func (g *goGenerator) serializeValue(expression string, typeRef semantic.Type) string {
	switch typeRef.Kind {
	case "money":
		return "moneyValue(" + expression + ")"
	case "time":
		return expression + ".UTC().Format(time.RFC3339Nano)"
	case "object":
		parts := []string{}
		for _, field := range typeRef.Fields {
			parts = append(parts, strconv.Quote(field.Name)+": "+g.serializeValue(expression+"."+g.fieldNames[typeRef.Name][field.Name], g.resolveType(field.Type)))
		}
		return "map[string]any{" + strings.Join(parts, ", ") + "}"
	default:
		return expression
	}
}

func (g *goGenerator) renderExpression(expression *ast.Expr, state *emitState) string {
	if expression == nil {
		return "nil"
	}
	switch expression.Kind {
	case "integer-literal":
		return "int64(" + strconv.Itoa(expression.Number) + ")"
	case "money-literal":
		return "moneyLiteral(" + strconv.Quote(expression.Currency) + ", " + strconv.Quote(expression.Unit) + ", " + strconv.Itoa(expression.Scale) + ", " + strconv.Quote(expression.Value) + ")"
	case "duration-literal":
		return "time.Duration(" + strconv.FormatInt(expression.Milliseconds, 10) + ") * time.Millisecond"
	case "reference":
		if symbol, ok := state.symbols[expression.Name]; ok {
			return symbol
		}
		if value, ok := g.valueNames[expression.Name]; ok {
			return value
		}
		return ""
	case "member":
		object := g.renderExpression(expression.Object, state)
		objectType := g.expressionType(expression.Object, state.environment)
		if fields := g.fieldNames[objectType.Name]; fields != nil {
			return object + "." + fields[expression.Property]
		}
		return object + ".F_" + encodeIdentifier(expression.Property)
	case "unary":
		return "!(" + g.renderExpression(expression.Expression, state) + ")"
	case "binary":
		left := g.renderExpression(expression.Left, state)
		right := g.renderExpression(expression.Right, state)
		leftType := g.expressionType(expression.Left, state.environment)
		if leftType.Kind == "money" && (expression.Operator == "+" || expression.Operator == "-") {
			if expression.Operator == "+" {
				return "moneyAdd(" + left + ", " + right + ")"
			}
			return "moneySubtract(" + left + ", " + right + ")"
		}
		if leftType.Kind == "money" && expression.Operator == "*" {
			return "moneyMultiply(" + left + ", " + right + ")"
		}
		if leftType.Kind == "money" && strings.Contains("> >= < <= == !=", expression.Operator) {
			comparison := map[string]string{"==": "== 0", "!=": "!= 0", ">": "> 0", ">=": ">= 0", "<": "< 0", "<=": "<= 0"}[expression.Operator]
			return "moneyCompare(" + left + ", " + right + ") " + comparison
		}
		if leftType.Kind == "time" && expression.Operator == "+" {
			return left + ".Add(" + right + ")"
		}
		if leftType.Kind == "time" && strings.Contains("> >= < <= == !=", expression.Operator) {
			comparison := map[string]string{"==": ".Equal(", "!=": ".Equal(", ">": ".After(", ">=": ".After(", "<": ".Before(", "<=": ".Before("}[expression.Operator]
			if expression.Operator == "==" || expression.Operator == "!=" {
				value := left + comparison + right + ")"
				if expression.Operator == "!=" {
					return "!(" + value + ")"
				}
				return value
			}
			value := left + comparison + right + ")"
			if expression.Operator == ">=" || expression.Operator == "<=" {
				return value + " || " + left + ".Equal(" + right + ")"
			}
			return value
		}
		operator := expression.Operator
		if operator == "and" {
			operator = "&&"
		}
		if operator == "or" {
			operator = "||"
		}
		if operator == "==" {
			operator = "=="
		}
		return "(" + left + " " + operator + " " + right + ")"
	}
	return ""
}

func (g *goGenerator) expressionType(expression *ast.Expr, environment map[string]semantic.Type) semantic.Type {
	if expression == nil {
		return semantic.Type{Kind: "unknown"}
	}
	switch expression.Kind {
	case "integer-literal":
		return semantic.Type{Kind: "integer"}
	case "money-literal":
		return semantic.Type{Kind: "money", Currency: expression.Currency, Unit: expression.Unit, Scale: expression.Scale}
	case "duration-literal":
		return semantic.Type{Kind: "duration"}
	case "reference":
		if value, ok := environment[expression.Name]; ok {
			return value
		}
		if typeName, ok := g.valueNames[expression.Name]; ok {
			for name, goName := range g.valueTypes {
				if strings.HasPrefix(typeName, goName+"(") {
					return semantic.Type{Kind: "value", Name: name}
				}
			}
		}
	case "member":
		container := g.expressionType(expression.Object, environment)
		for _, field := range container.Fields {
			if field.Name == expression.Property {
				return g.resolveType(field.Type)
			}
		}
	case "unary":
		return semantic.Type{Kind: "boolean"}
	case "binary":
		left := g.expressionType(expression.Left, environment)
		right := g.expressionType(expression.Right, environment)
		if expression.Operator == "and" || expression.Operator == "or" || strings.Contains("== != > >= < <=", expression.Operator) {
			return semantic.Type{Kind: "boolean"}
		}
		if expression.Operator == "*" && left.Kind == "money" {
			return left
		}
		if expression.Operator == "*" && right.Kind == "money" {
			return right
		}
		if expression.Operator == "+" && left.Kind == "time" {
			return left
		}
		return left
	}
	return semantic.Type{Kind: "unknown"}
}

func (g *goGenerator) goType(typeRef ast.TypeRef) string {
	return g.goSemanticType(g.resolveType(typeRef))
}

func (g *goGenerator) goSemanticType(typeRef semantic.Type) string {
	switch typeRef.Kind {
	case "integer":
		return "int64"
	case "text":
		return "string"
	case "boolean":
		return "bool"
	case "time":
		return "time.Time"
	case "duration":
		return "time.Duration"
	case "money":
		return "Money"
	case "value":
		if name := g.valueTypes[typeRef.Name]; name != "" {
			return name
		}
		return "string"
	case "object":
		return "*" + g.objectNames[typeRef.Name]
	case "record":
		return g.outputNames[typeRef.Name]
	default:
		return "any"
	}
}

func (g *goGenerator) resolveType(typeRef ast.TypeRef) semantic.Type {
	if typeRef.Kind == "named" || typeRef.Kind == "object" || typeRef.Kind == "value" {
		if value, ok := g.typeInfo.ObjectTypes[typeRef.Name]; ok {
			return value
		}
		if value, ok := g.typeInfo.ValueTypes[typeRef.Name]; ok {
			return value
		}
	}
	return semantic.Type{Kind: typeRef.Kind, Name: typeRef.Name, Currency: typeRef.Currency, Unit: typeRef.Unit, Scale: typeRef.Scale, Values: append([]string(nil), typeRef.Values...)}
}

func (g *goGenerator) valueEnvironment() map[string]semantic.Type {
	result := map[string]semantic.Type{}
	for _, valueType := range g.typeInfo.ValueTypes {
		for _, value := range valueType.Values {
			result[value] = valueType
		}
	}
	return result
}

func (g *goGenerator) flowInputEnvironment(flow ast.Flow) map[string]semantic.Type {
	result := g.valueEnvironment()
	for _, input := range flow.Inputs {
		result[input.Name] = g.resolveType(input.Type)
	}
	return result
}

func (g *goGenerator) currentFlowName(state *emitState) string {
	return state.flowName
}

func (g *goGenerator) identityExpression(expression string, object ast.Object) string {
	values := make([]string, 0, len(object.IdentityFields))
	for _, field := range object.IdentityFields {
		values = append(values, expression+"."+g.fieldNames[object.Name][field])
	}
	return "identityKey(" + strings.Join(values, ", ") + ")"
}

func findObject(objects []ast.Object, name string) (ast.Object, bool) {
	for _, object := range objects {
		if object.Name == name {
			return object, true
		}
	}
	return ast.Object{}, false
}
func findFlow(flows []ast.Flow, name string) (ast.Flow, bool) {
	for _, flow := range flows {
		if flow.Name == name {
			return flow, true
		}
	}
	return ast.Flow{}, false
}
func findAssignment(assignments []ast.Assignment, field string) *ast.Assignment {
	for index := range assignments {
		if assignments[index].Target != nil && assignments[index].Target.Property == field {
			return &assignments[index]
		}
	}
	return nil
}
func rootReference(expression *ast.Expr) string {
	for expression != nil && expression.Kind == "member" {
		expression = expression.Object
	}
	if expression != nil && expression.Kind == "reference" {
		return expression.Name
	}
	return ""
}
func cloneStrings(values map[string]string) map[string]string {
	clone := map[string]string{}
	for key, value := range values {
		clone[key] = value
	}
	return clone
}
func cloneTypes(values map[string]semantic.Type) map[string]semantic.Type {
	clone := map[string]semantic.Type{}
	for key, value := range values {
		clone[key] = value
	}
	return clone
}

func sortedKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func encodeIdentifier(value string) string {
	var b strings.Builder
	for _, runeValue := range value {
		if runeValue >= 'a' && runeValue <= 'z' || runeValue >= 'A' && runeValue <= 'Z' || runeValue >= '0' && runeValue <= '9' || runeValue == '_' {
			b.WriteRune(runeValue)
		} else {
			b.WriteString("u")
			b.WriteString(strconv.FormatInt(int64(runeValue), 16))
			b.WriteString("_")
		}
	}
	if b.Len() == 0 {
		return "anonymous"
	}
	return b.String()
}
