package backend

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/myczh-1/determinant/internal/ast"
	"github.com/myczh-1/determinant/internal/binding"
	"github.com/myczh-1/determinant/internal/semantic"
)

type TypeScriptBackend struct{ Binding *binding.Resolved }

func (TypeScriptBackend) Target() string { return "typescript" }

type tsGenerator struct {
	base *goGenerator
}

func (backend TypeScriptBackend) Generate(program *ast.Program, typeInfo *semantic.TypeInfo) (string, error) {
	if program == nil || typeInfo == nil {
		return "", fmt.Errorf("cannot generate TypeScript source without a checked program")
	}
	base := &goGenerator{
		program:      program,
		typeInfo:     typeInfo,
		objectNames:  map[string]string{},
		fieldNames:   map[string]map[string]string{},
		valueNames:   map[string]string{},
		flowNames:    map[string]string{},
		outputNames:  map[string]string{},
		valueTypes:   map[string]string{},
		usedNames:    map[string]bool{},
		flowCounters: map[string]int{},
		binding:      backend.Binding,
	}
	base.prepareNames()
	g := &tsGenerator{base: base}
	var b strings.Builder
	g.writeHeader(&b)
	g.writeRuntime(&b)
	g.writeValueTypes(&b)
	g.writeObjects(&b)
	g.writeStores(&b)
	g.writeFixtureLoader(&b)
	for _, flow := range program.Flows {
		g.writeFlow(&b, flow)
	}
	g.writeEntry(&b)
	g.writeHTTP(&b)
	return b.String(), nil
}

func (g *tsGenerator) writeHeader(b *strings.Builder) {
	b.WriteString("// Code generated by Determinant. DO NOT EDIT.\n")
	b.WriteString("// Application: " + strconv.Quote(g.base.program.Name) + "\n\n")
}

func (g *tsGenerator) writeRuntime(b *strings.Builder) {
	b.WriteString(`export type FlowResult<T> = { readonly ok: boolean; readonly value?: T; readonly error?: string };
export type Money = Readonly<{ kind: "money"; currency: string; unit: string; scale: number; minor: bigint }>;
export type Duration = Readonly<{ kind: "duration"; milliseconds: number }>;

function money(currency: string, unit: string, scale: number, text: string): Money {
  const value = text.trim();
  const negative = value.startsWith("-");
  const unsigned = negative ? value.slice(1) : value;
  const [whole, fraction = ""] = unsigned.split(".");
  if (!/^\d+$/.test(whole) || fraction.length > scale || !/^\d*$/.test(fraction)) throw new Error("invalid money");
  const padded = (fraction + "0".repeat(scale)).slice(0, scale);
  const base = 10n ** BigInt(scale);
  const minor = BigInt(whole) * base + BigInt(padded || "0");
  return { kind: "money", currency, unit, scale, minor: negative ? -minor : minor };
}

function moneyAdd(left: Money, right: Money): Money { assertMoney(left, right); return { ...left, minor: left.minor + right.minor }; }
function moneySubtract(left: Money, right: Money): Money { assertMoney(left, right); return { ...left, minor: left.minor - right.minor }; }
function moneyMultiply(value: Money, factor: number): Money { return { ...value, minor: value.minor * BigInt(factor) }; }
function moneyCompare(left: Money, right: Money): number { assertMoney(left, right); return left.minor < right.minor ? -1 : left.minor > right.minor ? 1 : 0; }
function assertMoney(left: Money, right: Money): void { if (left.currency !== right.currency || left.unit !== right.unit || left.scale !== right.scale) throw new Error("incompatible money"); }
function moneyValue(value: Money): string {
  const negative = value.minor < 0n;
  const absolute = negative ? -value.minor : value.minor;
  const base = 10n ** BigInt(value.scale);
  const whole = absolute / base;
  if (value.scale === 0) return (negative ? "-" : "") + whole;
  const fraction = (absolute % base).toString().padStart(value.scale, "0");
  return (negative ? "-" : "") + whole + "." + fraction;
}
function identityKey(...values: unknown[]): string { return JSON.stringify(values); }
function matchRoute(template: string, actual: string): { readonly [key: string]: string } | null {
  const clean = (value: string): string[] => { const trimmed = value.replace(/^\/+|\/+$/g, ""); return trimmed ? trimmed.split("/") : []; };
  const templateParts = clean(template), actualParts = clean(actual);
  if (templateParts.length !== actualParts.length) return null;
  const parameters: Record<string, string> = {};
  for (let index = 0; index < templateParts.length; index += 1) {
    const part = templateParts[index];
    if (part.startsWith("{") && part.endsWith("}")) { parameters[part.slice(1, -1)] = actualParts[index]; continue; }
    if (part !== actualParts[index]) return null;
  }
  return parameters;
}
function readBody(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function readInteger(value: unknown): number { if (typeof value === "number" && Number.isSafeInteger(value)) return value; if (typeof value === "string" && /^-?(?:0|[1-9]\d*)$/.test(value)) return Number(value); throw new Error("invalid integer"); }
function readText(value: unknown): string { if (typeof value === "string") return value; throw new Error("invalid text"); }
function readBoolean(value: unknown): boolean { if (typeof value === "boolean") return value; if (value === "true" || value === "false") return value === "true"; throw new Error("invalid boolean"); }
function readMoney(value: unknown, currency: string, unit: string, scale: number): Money { if (typeof value !== "string") throw new Error("invalid money"); const unsigned = value.startsWith("-") ? value.slice(1) : value; const parts = unsigned.split("."); if (parts.length !== 2 || parts[1].length !== scale || !/^\d+$/.test(parts[0]) || !/^\d+$/.test(parts[1]) || (parts[0].length > 1 && parts[0].startsWith("0"))) throw new Error("invalid money"); return money(currency, unit, scale, value); }
function readFixtureTime(value: unknown): Date { const parsed = new Date(readText(value)); if (!Number.isFinite(parsed.getTime()) || parsed.toISOString() !== value) throw new Error("invalid time"); return parsed; }
function readFixtureValue(value: unknown, allowed: readonly string[]): string { const text = readText(value); if (!allowed.includes(text)) throw new Error("invalid value"); return text; }

`)
}

func (g *tsGenerator) writeValueTypes(b *strings.Builder) {
	for _, valueSet := range g.base.program.ValueSets {
		name := g.base.valueTypes[valueSet.Name]
		values := make([]string, 0, len(valueSet.Values))
		for _, value := range valueSet.Values {
			values = append(values, strconv.Quote(value.Name))
			b.WriteString("export const " + "Value_" + encodeIdentifier(value.Name) + " = " + strconv.Quote(value.Name) + " as " + name + "\n")
		}
		b.WriteString("export type " + name + " = " + strings.Join(values, " | ") + ";\n\n")
	}
}

func (g *tsGenerator) writeObjects(b *strings.Builder) {
	for _, object := range g.base.program.Objects {
		b.WriteString("export type " + g.base.objectNames[object.Name] + " = {\n")
		for _, field := range object.Fields {
			b.WriteString("  " + g.base.fieldNames[object.Name][field.Name] + ": " + g.tsType(g.base.resolveType(field.Type)) + ";\n")
		}
		b.WriteString("};\n\n")
	}
}

func (g *tsGenerator) writeStores(b *strings.Builder) {
	for _, object := range g.base.program.Objects {
		if len(object.IdentityFields) > 0 {
			b.WriteString("const store_" + encodeIdentifier(object.Name) + " = new Map<string, " + g.base.objectNames[object.Name] + ">();\n")
		}
	}
	if len(g.base.program.Objects) > 0 {
		b.WriteString("\n")
	}
}

func (g *tsGenerator) writeFixtureLoader(b *strings.Builder) {
	stored := make([]ast.Object, 0)
	for _, object := range g.base.program.Objects {
		if len(object.IdentityFields) > 0 {
			stored = append(stored, object)
		}
	}
	b.WriteString("export function loadFixture(input: unknown): void {\n")
	b.WriteString("  const root = readBody(input);\n")
	b.WriteString("  if (Object.keys(root).length !== " + strconv.Itoa(len(stored)) + ") throw new Error(\"invalid fixture: unexpected object set\");\n")
	for _, object := range stored {
		name := encodeIdentifier(object.Name)
		b.WriteString("  if (!(" + strconv.Quote(object.Name) + " in root)) throw new Error(" + strconv.Quote("invalid fixture: missing "+object.Name) + ");\n")
		b.WriteString("  const rows_" + name + " = root[" + strconv.Quote(object.Name) + "];\n")
		b.WriteString("  if (!Array.isArray(rows_" + name + ")) throw new Error(" + strconv.Quote("invalid fixture: "+object.Name) + ");\n")
		b.WriteString("  const fixtureStore_" + name + " = new Map<string, " + g.base.objectNames[object.Name] + ">();\n")
		b.WriteString("  for (const row of rows_" + name + ") {\n")
		b.WriteString("    const item = readBody(row);\n")
		b.WriteString("    if (Object.keys(item).length !== " + strconv.Itoa(len(object.Fields)) + ") throw new Error(" + strconv.Quote("invalid fixture: "+object.Name+" fields") + ");\n")
		b.WriteString("    const value: " + g.base.objectNames[object.Name] + " = {\n")
		for _, field := range object.Fields {
			b.WriteString("      " + g.base.fieldNames[object.Name][field.Name] + ": " + g.fixtureValueExpression(field.Type, "item["+strconv.Quote(field.Name)+"]") + ",\n")
		}
		b.WriteString("    };\n")
		b.WriteString("    const key = " + g.identityExpression("value", object) + ";\n")
		b.WriteString("    if (fixtureStore_" + name + ".has(key)) throw new Error(" + strconv.Quote("invalid fixture: duplicate "+object.Name+" identity") + ");\n")
		b.WriteString("    fixtureStore_" + name + ".set(key, value);\n  }\n")
	}
	for _, object := range stored {
		name := encodeIdentifier(object.Name)
		b.WriteString("  store_" + name + ".clear();\n  for (const [key, value] of fixtureStore_" + name + ") store_" + name + ".set(key, value);\n")
	}
	b.WriteString("}\n\n")
}

func (g *tsGenerator) fixtureValueExpression(typeRef ast.TypeRef, value string) string {
	resolved := g.base.resolveType(typeRef)
	switch resolved.Kind {
	case "integer":
		return "readInteger(" + value + ")"
	case "text":
		return "readText(" + value + ")"
	case "boolean":
		return "readBoolean(" + value + ")"
	case "money":
		return "readMoney(" + value + ", " + strconv.Quote(resolved.Currency) + ", " + strconv.Quote(resolved.Unit) + ", " + strconv.Itoa(resolved.Scale) + ")"
	case "time":
		return "readFixtureTime(" + value + ")"
	case "value":
		allowed := make([]string, 0, len(resolved.Values))
		for _, candidate := range resolved.Values {
			allowed = append(allowed, strconv.Quote(candidate))
		}
		return "readFixtureValue(" + value + ", [" + strings.Join(allowed, ", ") + "]) as " + g.base.valueTypes[resolved.Name]
	default:
		return "(() => { throw new Error(\"invalid fixture: unsupported field type\") })() as never"
	}
}

func (g *tsGenerator) writeFlow(b *strings.Builder, flow ast.Flow) {
	signature := g.base.typeInfo.FlowSignatures[flow.Name]
	outputName := g.base.outputNames[flow.Name]
	b.WriteString("export type " + outputName + " = {\n")
	for index, output := range flow.Outputs {
		outputType := semantic.Type{Kind: "unknown"}
		if index < len(signature.Output.Fields) {
			outputType = g.base.resolveType(signature.Output.Fields[index].Type)
		}
		b.WriteString("  " + g.base.outputFieldName(flow.Name, output.Name) + ": " + g.tsType(outputType) + ";\n")
	}
	b.WriteString("};\n\n")

	params := make([]string, 0, len(flow.Inputs))
	state := &tsEmitState{symbols: map[string]string{}, environment: g.base.valueEnvironment(), counters: map[string]int{}, flowName: flow.Name}
	for index, input := range flow.Inputs {
		parameter := fmt.Sprintf("input_%d", index)
		params = append(params, parameter+": "+g.tsType(g.base.resolveType(input.Type)))
		state.symbols[input.Name] = parameter
		state.environment[input.Name] = g.base.resolveType(input.Type)
	}
	b.WriteString("function " + g.base.flowNames[flow.Name] + "(" + strings.Join(params, ", ") + "): FlowResult<" + outputName + "> {\n")
	g.emitStatements(b, flow.Statements, state, "  ", nil)
	b.WriteString("  return { ok: true, value: {\n")
	for _, output := range flow.Outputs {
		b.WriteString("    " + g.base.outputFieldName(flow.Name, output.Name) + ": " + g.renderExpression(output.Expression, state) + ",\n")
	}
	b.WriteString("  } };\n}\n\n")
}

type tsEmitState struct {
	symbols     map[string]string
	environment map[string]semantic.Type
	counters    map[string]int
	flowName    string
}

type tsAtomicState struct {
	original map[string]string
	staged   map[string]string
	pending  []tsPendingCreate
}

type tsPendingCreate struct{ object, symbol, key string }

func (g *tsGenerator) emitStatements(b *strings.Builder, statements []ast.Statement, state *tsEmitState, indent string, atomic *tsAtomicState) {
	for _, statement := range statements {
		switch statement.Kind {
		case "if":
			b.WriteString(indent + "if (" + g.renderExpression(statement.Condition, state) + ") return { ok: false, error: " + strconv.Quote(statement.Failure) + " };\n")
		case "conditional":
			b.WriteString(indent + "if (" + g.renderExpression(statement.Condition, state) + ") {\n")
			child := &tsEmitState{symbols: cloneStrings(state.symbols), environment: cloneTypes(state.environment), counters: state.counters, flowName: state.flowName}
			g.emitStatements(b, statement.Statements, child, indent+"  ", atomic)
			b.WriteString(indent + "}\n")
		case "atomic":
			g.emitAtomic(b, statement.Statements, state, indent)
		case "calculate":
			name := fmt.Sprintf("calculation_%d", state.counters["calculate"])
			state.counters["calculate"]++
			b.WriteString(indent + "const " + name + " = " + g.renderExpression(statement.Expression, state) + ";\n")
			state.symbols[statement.Name] = name
			state.environment[statement.Name] = g.base.expressionType(statement.Expression, state.environment)
		case "create":
			g.emitCreate(b, statement, state, indent, atomic)
		case "query":
			g.emitQuery(b, statement, state, indent)
		case "delete":
			g.emitDelete(b, statement, state, indent)
		case "change":
			b.WriteString(indent + g.renderExpression(statement.Target, state) + " = " + g.renderExpression(statement.Expression, state) + ";\n")
		case "execute":
			g.emitExecute(b, statement, state, indent)
		}
	}
}

func (g *tsGenerator) emitAtomic(b *strings.Builder, statements []ast.Statement, state *tsEmitState, indent string) {
	transaction := &tsAtomicState{original: map[string]string{}, staged: map[string]string{}}
	for _, statement := range statements {
		if statement.Kind != "change" {
			continue
		}
		root := rootReference(statement.Target)
		original := state.symbols[root]
		if root == "" || original == "" || transaction.staged[root] != "" {
			continue
		}
		staged := fmt.Sprintf("atomic_%d", len(transaction.staged))
		b.WriteString(indent + "const " + staged + " = { ..." + original + " };\n")
		transaction.original[root] = original
		transaction.staged[root] = staged
	}
	child := &tsEmitState{symbols: cloneStrings(state.symbols), environment: cloneTypes(state.environment), counters: state.counters, flowName: state.flowName}
	for root, staged := range transaction.staged {
		child.symbols[root] = staged
	}
	g.emitStatements(b, statements, child, indent, transaction)
	for _, root := range sortedKeys(transaction.staged) {
		b.WriteString(indent + "Object.assign(" + transaction.original[root] + ", " + transaction.staged[root] + ");\n")
	}
	for _, pending := range transaction.pending {
		b.WriteString(indent + "store_" + encodeIdentifier(pending.object) + ".set(" + pending.key + ", " + pending.symbol + ");\n")
	}
}

func (g *tsGenerator) emitCreate(b *strings.Builder, statement ast.Statement, state *tsEmitState, indent string, atomic *tsAtomicState) {
	object, ok := findObject(g.base.program.Objects, statement.ObjectName)
	if !ok {
		return
	}
	symbol := fmt.Sprintf("created_%d", state.counters["create"])
	state.counters["create"]++
	b.WriteString(indent + "const " + symbol + ": " + g.base.objectNames[object.Name] + " = {\n")
	for _, field := range object.Fields {
		if assignment := findAssignment(statement.Assignments, field.Name); assignment != nil {
			b.WriteString(indent + "  " + g.base.fieldNames[object.Name][field.Name] + ": " + g.renderExpression(assignment.Expression, state) + ",\n")
		}
	}
	b.WriteString(indent + "};\n")
	key := symbol + "_key"
	b.WriteString(indent + "const " + key + " = " + g.identityExpression(symbol, object) + ";\n")
	store := "store_" + encodeIdentifier(object.Name)
	b.WriteString(indent + "if (" + store + ".has(" + key + ")) return { ok: false, error: " + strconv.Quote(statement.Failure) + " };\n")
	if atomic != nil {
		for _, pending := range atomic.pending {
			if pending.object == object.Name {
				b.WriteString(indent + "if (" + pending.key + " === " + key + ") return { ok: false, error: " + strconv.Quote(statement.Failure) + " };\n")
			}
		}
		atomic.pending = append(atomic.pending, tsPendingCreate{object: object.Name, symbol: symbol, key: key})
	} else {
		b.WriteString(indent + store + ".set(" + key + ", " + symbol + ");\n")
	}
	state.symbols[statement.Name] = symbol
	state.environment[statement.Name] = g.base.resolveType(ast.TypeRef{Kind: "named", Name: object.Name})
}

func (g *tsGenerator) emitQuery(b *strings.Builder, statement ast.Statement, state *tsEmitState, indent string) {
	object, ok := findObject(g.base.program.Objects, statement.ObjectName)
	if !ok {
		return
	}
	candidate := fmt.Sprintf("query_candidate_%d", state.counters["query"])
	symbol := fmt.Sprintf("query_%d", state.counters["query"])
	state.counters["query"]++
	b.WriteString(indent + "let " + symbol + ": " + g.base.objectNames[object.Name] + " | undefined;\n")
	b.WriteString(indent + "for (const " + candidate + " of store_" + encodeIdentifier(object.Name) + ".values()) {\n")
	queryState := &tsEmitState{symbols: cloneStrings(state.symbols), environment: cloneTypes(state.environment), counters: state.counters, flowName: state.flowName}
	queryState.symbols[statement.Name] = candidate
	queryState.environment[statement.Name] = g.base.resolveType(ast.TypeRef{Kind: "named", Name: object.Name})
	b.WriteString(indent + "  if (" + g.renderExpression(statement.Condition, queryState) + ") { " + symbol + " = " + candidate + "; break; }\n")
	b.WriteString(indent + "}\n")
	b.WriteString(indent + "if (!" + symbol + ") return { ok: false, error: " + strconv.Quote(statement.Failure) + " };\n")
	state.symbols[statement.Name] = symbol
	state.environment[statement.Name] = g.base.resolveType(ast.TypeRef{Kind: "named", Name: object.Name})
}

func (g *tsGenerator) emitDelete(b *strings.Builder, statement ast.Statement, state *tsEmitState, indent string) {
	if statement.Expression == nil || statement.Expression.Kind != "reference" {
		return
	}
	typeInfo := state.environment[statement.Expression.Name]
	object, ok := findObject(g.base.program.Objects, typeInfo.Name)
	if !ok {
		return
	}
	b.WriteString(indent + "store_" + encodeIdentifier(object.Name) + ".delete(" + g.identityExpression(g.renderExpression(statement.Expression, state), object) + ");\n")
}

func (g *tsGenerator) emitExecute(b *strings.Builder, statement ast.Statement, state *tsEmitState, indent string) {
	called, ok := g.base.typeInfo.FlowSignatures[statement.FlowName]
	if !ok {
		return
	}
	result := fmt.Sprintf("executed_%d", state.counters["execute"])
	state.counters["execute"]++
	args := make([]string, 0, len(statement.Inputs))
	for _, input := range statement.Inputs {
		args = append(args, g.renderExpression(input, state))
	}
	b.WriteString(indent + "const " + result + " = " + g.base.flowNames[statement.FlowName] + "(" + strings.Join(args, ", ") + ");\n")
	b.WriteString(indent + "if (!" + result + ".ok) return { ok: false, error: " + result + ".error };\n")
	for index, output := range statement.Outputs {
		if index < len(called.Output.Fields) {
			field := called.Output.Fields[index]
			state.symbols[output] = result + ".value." + g.base.outputFieldName(statement.FlowName, field.Name)
			state.environment[output] = g.base.resolveType(field.Type)
		}
	}
}

func (g *tsGenerator) writeEntry(b *strings.Builder) {
	if len(g.base.program.Flows) == 0 {
		return
	}
	entry := g.base.program.Flows[len(g.base.program.Flows)-1]
	signature := g.base.typeInfo.FlowSignatures[entry.Name]
	b.WriteString("export type Input = {\n")
	for _, input := range entry.Inputs {
		b.WriteString("  " + g.base.inputProgramName(entry.Name, input.Name) + ": " + g.tsType(g.base.resolveType(input.Type)) + ";\n")
	}
	b.WriteString("};\nexport type Output = " + g.base.outputNames[entry.Name] + ";\n")
	b.WriteString("export function run(input: Input): FlowResult<Output> { return " + g.base.flowNames[entry.Name] + "(" + g.entryArguments(entry, signature) + "); }\n\n")
}

func (g *tsGenerator) entryArguments(flow ast.Flow, signature semantic.FlowSignature) string {
	args := make([]string, 0, len(signature.Inputs))
	for _, input := range signature.Inputs {
		args = append(args, "input["+strconv.Quote(g.base.inputProgramName(flow.Name, input.Name))+"]")
	}
	return strings.Join(args, ", ")
}

func (g *tsGenerator) writeHTTP(b *strings.Builder) {
	if len(g.base.program.HTTPEntries) == 0 {
		return
	}
	b.WriteString(`export interface HttpRequest { readonly method: string; readonly path: string; readonly body?: unknown; }
export interface HttpResponse { readonly status: number; readonly body?: unknown; }
export interface HttpRuntimeContext { readonly now?: () => string | number | Date; }

function auditValue(value: unknown): unknown {
  if (value && typeof value === "object" && (value as Money).kind === "money") return moneyValue(value as Money);
  if (value instanceof Date) return value.toISOString();
  return value;
}

export function handleHttpRequest(request: HttpRequest, context: HttpRuntimeContext = {}): HttpResponse {
`)
	for _, entry := range g.base.program.HTTPEntries {
		flow, ok := findFlow(g.base.program.Flows, entry.TargetFlow)
		if !ok {
			continue
		}
		b.WriteString("  if (request.method.toUpperCase() === " + strconv.Quote(entry.Method) + ") {\n")
		b.WriteString("    const parameters = matchRoute(" + strconv.Quote(entry.Path) + ", request.path.split(\"?\", 1)[0] || \"/\");\n")
		b.WriteString("    if (parameters) {\n")
		if len(entry.BodyMappings) > 0 {
			b.WriteString("      const body = readBody(request.body);\n")
		} else {
			b.WriteString("      const body: Record<string, unknown> = {};\n")
		}
		for index, input := range flow.Inputs {
			mapping, source, fromPath := g.base.httpMapping(entry, input.Name)
			variable := fmt.Sprintf("input_%d", index)
			if source == "system" {
				b.WriteString("      const " + variable + " = context.now ? new Date(context.now()) : new Date();\n")
				continue
			}
			value := "parameters[" + strconv.Quote(mapping.SourceName) + "]"
			if !fromPath {
				value = "body[" + strconv.Quote(mapping.SourceName) + "]"
			}
			b.WriteString("      let " + variable + ": " + g.tsType(g.base.resolveType(input.Type)) + ";\n")
			b.WriteString("      try { " + variable + " = " + g.httpReader(input.Type, value, fromPath) + "; } catch { return { status: 400, body: { error: \"invalid request field\" } }; }\n")
		}
		args := make([]string, 0, len(flow.Inputs))
		for index := range flow.Inputs {
			args = append(args, fmt.Sprintf("input_%d", index))
		}
		result := "httpResult_" + encodeIdentifier(entry.Name)
		b.WriteString("      const " + result + " = " + g.base.flowNames[flow.Name] + "(" + strings.Join(args, ", ") + ");\n")
		b.WriteString("      if (!" + result + ".ok) {\n")
		for _, failure := range entry.FailureMappings {
			b.WriteString("        if (" + result + ".error === " + strconv.Quote(failure.Failure) + ") return { status: " + strconv.Itoa(failure.Status) + ", body: { error: " + result + ".error } };\n")
		}
		b.WriteString("        return { status: 500, body: { error: " + result + ".error } };\n      }\n")
		if entry.SuccessStatus == 204 {
			b.WriteString("      return { status: 204 };\n")
		} else {
			b.WriteString("      return { status: " + strconv.Itoa(entry.SuccessStatus) + ", body: {\n")
			signature := g.base.typeInfo.FlowSignatures[flow.Name]
			for _, output := range signature.Output.Fields {
				expression := result + ".value." + g.base.outputFieldName(flow.Name, output.Name)
				b.WriteString("        " + strconv.Quote(output.Name) + ": " + g.serializeValue(expression, g.base.resolveType(output.Type)) + ",\n")
			}
			b.WriteString("      } };\n")
		}
		b.WriteString("    }\n  }\n")
	}
	b.WriteString("  return { status: 404, body: { error: \"route not found\" } };\n}\n")
}

func (g *tsGenerator) httpReader(typeRef ast.TypeRef, value string, fromPath bool) string {
	typeInfo := g.base.resolveType(typeRef)
	switch typeInfo.Kind {
	case "integer":
		return "readInteger(" + value + ")"
	case "boolean":
		return "readBoolean(" + value + ")"
	case "money":
		return "readMoney(" + value + ", " + strconv.Quote(typeInfo.Currency) + ", " + strconv.Quote(typeInfo.Unit) + ", " + strconv.Itoa(typeInfo.Scale) + ")"
	default:
		return "readText(" + value + ")"
	}
}

func (g *tsGenerator) serializeValue(expression string, typeRef semantic.Type) string {
	switch typeRef.Kind {
	case "money":
		return "moneyValue(" + expression + ")"
	case "time":
		return expression + ".toISOString()"
	case "object":
		parts := make([]string, 0, len(typeRef.Fields))
		for _, field := range typeRef.Fields {
			parts = append(parts, strconv.Quote(field.Name)+": "+g.serializeValue(expression+"."+g.base.fieldNames[typeRef.Name][field.Name], g.base.resolveType(field.Type)))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	default:
		return expression
	}
}

func (g *tsGenerator) identityExpression(expression string, object ast.Object) string {
	values := make([]string, 0, len(object.IdentityFields))
	for _, field := range object.IdentityFields {
		values = append(values, expression+"."+g.base.fieldNames[object.Name][field])
	}
	return "identityKey(" + strings.Join(values, ", ") + ")"
}

func (g *tsGenerator) renderExpression(expression *ast.Expr, state *tsEmitState) string {
	if expression == nil {
		return "undefined"
	}
	switch expression.Kind {
	case "integer-literal":
		return strconv.Itoa(expression.Number)
	case "money-literal":
		return "money(" + strconv.Quote(expression.Currency) + ", " + strconv.Quote(expression.Unit) + ", " + strconv.Itoa(expression.Scale) + ", " + strconv.Quote(expression.Value) + ")"
	case "duration-literal":
		return "{ kind: \"duration\", milliseconds: " + strconv.FormatInt(expression.Milliseconds, 10) + " }"
	case "reference":
		if symbol, ok := state.symbols[expression.Name]; ok {
			return symbol
		}
		if _, ok := g.base.valueNames[expression.Name]; ok {
			return "Value_" + encodeIdentifier(expression.Name)
		}
		return "undefined"
	case "member":
		return g.renderExpression(expression.Object, state) + "." + g.base.fieldNames[g.base.expressionType(expression.Object, state.environment).Name][expression.Property]
	case "unary":
		return "!(" + g.renderExpression(expression.Expression, state) + ")"
	case "binary":
		left, right := g.renderExpression(expression.Left, state), g.renderExpression(expression.Right, state)
		leftType := g.base.expressionType(expression.Left, state.environment)
		if leftType.Kind == "money" && expression.Operator == "+" {
			return "moneyAdd(" + left + ", " + right + ")"
		}
		if leftType.Kind == "money" && expression.Operator == "-" {
			return "moneySubtract(" + left + ", " + right + ")"
		}
		if leftType.Kind == "money" && expression.Operator == "*" {
			return "moneyMultiply(" + left + ", " + right + ")"
		}
		if leftType.Kind == "money" && strings.Contains("> >= < <= == !=", expression.Operator) {
			return "moneyCompare(" + left + ", " + right + ") " + map[string]string{"==": "=== 0", "!=": "!== 0", ">": "> 0", ">=": ">= 0", "<": "< 0", "<=": "<= 0"}[expression.Operator]
		}
		if leftType.Kind == "time" && expression.Operator == "+" {
			return "new Date(" + left + ".getTime() + " + right + ".milliseconds)"
		}
		if leftType.Kind == "time" && strings.Contains("> >= < <= == !=", expression.Operator) {
			l, r := left+".getTime()", right+".getTime()"
			op := expression.Operator
			return "(" + l + " " + op + " " + r + ")"
		}
		op := expression.Operator
		if op == "and" {
			op = "&&"
		}
		if op == "or" {
			op = "||"
		}
		return "(" + left + " " + op + " " + right + ")"
	}
	return "undefined"
}

func (g *tsGenerator) tsType(typeRef semantic.Type) string {
	switch typeRef.Kind {
	case "integer":
		return "number"
	case "text":
		return "string"
	case "boolean":
		return "boolean"
	case "time":
		return "Date"
	case "duration":
		return "Duration"
	case "money":
		return "Money"
	case "value":
		if name := g.base.valueTypes[typeRef.Name]; name != "" {
			return name
		}
		return "string"
	case "object":
		return g.base.objectNames[typeRef.Name]
	case "record":
		return g.base.outputNames[typeRef.Name]
	default:
		return "unknown"
	}
}
